# target: src/monte_carlo.py

monte_carlo_config:
  n_max: 5000
  n_step: 50

  k_1: 5
  k_2: 50

  functions: 
    - key: "Fn1" 
      a: 0
      b: 8
      fn: "x**(1/3)"  
      exac_value: 12.0

    - key: "Fn2"
      a: 0
      b: 3.141592653589793
      fn: "sin(x)"
      exac_value: 2.0

    - key: "Fn3"
      a: 0
      b: 1
      fn: "4*x*(1-x)**3" 
      exac_value: 0.2
